### ISSUE TITLE
ChoiceCheckBoxDialog predefined choices

### ISSUE THREAD

**Issue by JEuler** [ricardocrescenti/flutter-standard-dialogs#2]
Hi! Cool package, but maybe you already implemented or planning to add the functionality for predefined choices. Like, I want all items to be selected in ChoiceCheckBoxDialog, and then deselect them if not needed.

**Comment by ricardocrescenti** [comment]
Hello, thanks for the suggestion, I just released version 2.1.0 with this functionality, just inform the `checked` option in the `DialogChoice` class

**Comment by JEuler** [comment]
Thank you, cool!
