### ISSUE TITLE
Change color of dialogs

### ISSUE THREAD

**Issue by schube** [ricardocrescenti/flutter-standard-dialogs#3]
Hi!

(How) is it possible, to change the colors of SucsessDialog, WarningDialog or ErrorDialog?
Since we use slightly different colors in our app, I would like to change the colors in the dialog to match the colors in the app.

I did not find any setting/parameter to change the predefined colors.

Thank you,
schube

**Comment by ricardocrescenti** [comment]
Hey how's it going?

Currently the colors of these dialogs are fixed, however you can create your own methods by modifying these colors, for that you can access the file `lib/dialogs/result_dialog.dart`, copy the methods `showSuccessDialog`, `showWarningDialog` and `showErrorDialog ` to a class in your project and change the `backgroundColor` property with your colors

**Comment by schube** [comment]
Thank you!
Might try that for the next project. In the meantime we switched to another library, because we needed to change the colors. Thank you!
